// data.dart
import 'screens/home_page/service_card.dart';

// Static service data
final List<ServiceModel> serviceData = [
  ServiceModel(
    imageUrl: 'assets/images/image1.jpg',
    title: 'Professional Home Care Service',
    rating: 4.8,
    price: '\$20/hr',
    location: 'Available in New York & Nearby Areas',
    experience: '5+ Years of Experience',
    description: 'Our professional caregivers provide compassionate support for seniors and individuals with special needs. Services include personal care, medication reminders, companionship, and meal preparation. We ensure safety and comfort for your loved ones at home.',
    features: [
      'Certified and Background-Checked Caregivers',
      '24/7 On-Demand Support',
      'Customized Care Plans for Every Client',
      'Assistance with Daily Activities',
      'Medication Management and Meal Prep',
    ],
  ),
  ServiceModel(
    imageUrl: 'assets/images/image2.jpg',
    title: 'Companion Care',
    rating: 4.5,
    price: '\$25/hr',
    location: 'Available in Los Angeles & Nearby Areas',
    experience: '7+ Years of Experience',
    description: 'Compassionate companion care services for seniors who need social interaction and assistance with daily tasks. Our caregivers provide friendly companionship, help with errands, and ensure your loved ones feel supported.',
    features: [
      'Friendly and Professional Companions',
      'Help with Daily Errands and Shopping',
      'Social Activities and Engagement',
      'Transportation Assistance',
      'Light Housekeeping Support',
    ],
  ),
  ServiceModel(
    imageUrl: 'assets/images/image3.jpg',
    title: 'Family Caregiver Support',
    rating: 4.3,
    price: '\$18.50/hr',
    location: 'Available in Chicago & Nearby Areas',
    experience: '4+ Years of Experience',
    description: 'Supporting family caregivers with respite care and professional assistance. We understand the challenges of family caregiving and provide reliable support to give you peace of mind.',
    features: [
      'Respite Care for Family Caregivers',
      'Flexible Scheduling Options',
      'Experienced and Trustworthy Staff',
      'Personal Care Assistance',
      'Emotional Support and Guidance',
    ],
  ),
  ServiceModel(
    imageUrl: 'assets/images/image4.jpg',
    title: 'Geriatric Caregiver',
    rating: 4.7,
    price: '\$22/hr',
    location: 'Available in Miami & Nearby Areas',
    experience: '6+ Years of Experience',
    description: 'Specialized geriatric care for elderly patients with complex health needs. Our trained caregivers provide expert care including mobility assistance, cognitive support, and chronic disease management.',
    features: [
      'Specialized Training in Geriatric Care',
      'Mobility and Transfer Assistance',
      'Cognitive Stimulation Activities',
      'Chronic Disease Management',
      'Fall Prevention Strategies',
    ],
  ),
  ServiceModel(
    imageUrl: 'assets/images/image5.jpg',
    title: 'Home Health Aide',
    rating: 4.9,
    price: '\$24/hr',
    location: 'Available in Boston & Nearby Areas',
    experience: '8+ Years of Experience',
    description: 'Professional home health aides providing medical support and personal care. Our certified aides work under physician guidance to deliver quality healthcare at home.',
    features: [
      'Certified Home Health Aides',
      'Vital Sign Monitoring',
      'Wound Care and Dressing Changes',
      'Assistance with Medical Equipment',
      'Coordination with Healthcare Providers',
    ],
  ),
  ServiceModel(
    imageUrl: 'assets/images/image6.jpg',
    title: 'Respite Care',
    rating: 4.6,
    price: '\$21/hr',
    location: 'Available in Seattle & Nearby Areas',
    experience: '5+ Years of Experience',
    description: 'Temporary relief care for primary caregivers. Our respite care services allow family caregivers to take a break while ensuring their loved ones receive quality care.',
    features: [
      'Short-term and Long-term Options',
      'Day and Overnight Care Available',
      'Activities and Engagement Programs',
      'Safe and Comfortable Environment',
      'Regular Updates to Family Members',
    ],
  ),
];